### ISSUE TITLE
Project Goals and Ideas

### ISSUE THREAD

**Issue by stripethree** [stripethree/slack-events-relay#3]
Things I am interested in pursuing with this project. All of them will be overkill, so I am treating this as a list of potentially useful things that I might toy with.

* [x] continuous integration, perhaps with [_Travis CI_](https://travis-ci.org/) since I haven't used it before, or with [_Codeship_](https://codeship.com/) (#8 & #9)
* [x] deployment to [_Heroku_](https://www.heroku.com/) or something similar ([here](https://stripethree-slack-events-relay.herokuapp.com/))
* ~🤔about [_Splunk_](https://www.splunk.com/) for logging, but since this app is meant as an event logger, that might be overkill~ maybe later
* [x] hook it up to [_Code Climate_](https://codeclimate.com/) (#4)
* [x] experiment with GitHub templates (#2)
* [x] experiment with lint setups? (#6)
* [x] monitoring? Sentry/Pingdom/whatever? (#10, Pingdom set up on default Heroku route)
* ~[Renovate?](https://github.com/marketplace/renovate)~
